### ISSUE TITLE
Error: `LngLatLike` argument must be specified as a LngLat instance, an object {lng: <lng>, lat: <lat>},...

### ISSUE THREAD

**Issue by karlguillotte** [avalanche-canada/ac-web#111]
Clicking two times on an active region trigger the error below! 

https://sentry.io/avalanche-canada/ac-web/issues/312961742/

```
Error: `LngLatLike` argument must be specified as a LngLat instance, an object {lng: <lng>, lat: <lat>}, or an array of [<lng>, <lat>]
  at setLngLat (./client/containers/Map.js:192:19)
  at showClusterPopup (./client/containers/Map.js:156:29)
...
(3 additional frame(s) were not displayed)
```

**Comment by karlguillotte** [comment]
Fix in https://github.com/avalanche-canada/ac-web/commit/5da3bae9ea2efb7d1ce9f5f190e64cceb33c61f9
